### PR TITLE
updated output file with subnet and vnet id's on output for reference

### PR DESCRIPTION
**Pull request by satyamuralidhar**

### CODE REVIEW

**Comment by jvhoof** [comment]
Hi Satya,

This seems good to add. Just want to understand you commit. Is this to help you deployment process where you need these id's in subsequent stages? Do you also want these output for other products?

Joeri

**Comment by satyamuralidhar** [comment]
You absolutely right but if we want know ids of vnet and subnet every we need to check manually or cmd like . While using our plan we can known easily

**Comment by jvhoof** [comment]
Sounds good. We'll approve this and add it to the other templates as well.

thanks,

Joeri

**Comment by satyamuralidhar** [comment]
Pls add me as a member for this project bro

**Review by satyamuralidhar — COMMENTED** [review]
to know subnet and vnet id's

**Pull request merged**
